version: '3'

volumes:
  am-db-data:

services:
  web:
    build: .
    command: ./setup.sh
    image: 'scd53n00/attendance-management'
    container_name: 'attendance-management'
    expose:
        - "8001"
    volumes:
      - '.:/home/attendance-management'
    environment:
      - 'DATABASE_PASSWORD=postgres'
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'PGTZ=Asia/Tokyo'
    volumes:
      - 'am-db-data:/var/lib/postgresql/data'

  nginx:
    image: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./mysite/static:/static
    depends_on:
      - web