version: '3'

services:
  web:
    build: .
    image: 'scd53n00/attendance-management'
    container_name: 'attendance-management'
    ports:
      - '8000:8000'
    volumes:
      - '.:/home/attendance-management'
    tty: true
    stdin_open: true